
service: api-traductor

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: api
          method: post
          cors: true
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: api
          method: get
          cors: true
  readOne:
    handler: handler.readOne
    events:
      - http:
          path: api/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: api/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: api/{id}
          method: delete
          cors: true

resources:
  Resources:
    ApiDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'api' 

